# Generated by Django 5.1.4 on 2025-01-27 02:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='council_id',
            new_name='council',
        ),
        migrations.RenameField(
            model_name='feedbacks',
            old_name='council_id',
            new_name='council',
        ),
        migrations.RenameField(
            model_name='projects',
            old_name='council_id',
            new_name='council',
        ),
        migrations.RenameField(
            model_name='requests',
            old_name='council_id',
            new_name='council',
        ),
    ]
