# Generated by Django 5.1.4 on 2025-01-27 03:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_council_id_customuser_council_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='council',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='userCouncil', to='api.council', to_field='name'),
        ),
    ]
