# Generated by Django 5.1.4 on 2025-03-27 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_council_projectimages_projects_feedbacks_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='brief',
            field=models.CharField(default='This is a short paragraph describing the project', max_length=300),
            preserve_default=False,
        ),
    ]
