# Generated by Django 5.1.4 on 2025-03-28 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_projects_brief'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='location',
            field=models.CharField(default='Nouvelle Route, Bonabo', max_length=100),
            preserve_default=False,
        ),
    ]
