# Generated by Django 5.1.4 on 2025-03-28 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_projects_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contributions',
            name='contact_method',
        ),
        migrations.AlterField(
            model_name='contributions',
            name='amount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contributions',
            name='description',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='contributions',
            name='time_commit',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
