# Generated by Django 5.1.4 on 2025-04-07 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_contributions_contact_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contributions',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Reviewed', 'Reviewed')], default='Pending', max_length=20),
        ),
    ]
