# Generated by Django 5.1.4 on 2025-03-08 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_customuser_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='username',
        ),
    ]
