# Generated by Django 5.1.4 on 2025-03-12 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_remove_customuser_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requests',
            name='text',
        ),
        migrations.AddField(
            model_name='contributions',
            name='add_comments',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='contributions',
            name='amount',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contributions',
            name='contact_method',
            field=models.CharField(choices=[('Phone', 'Phone'), ('Email', 'Email'), ('WhatsApp', 'WhatsApp')], default='email', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contributions',
            name='contrib_type',
            field=models.CharField(choices=[('Financial', 'Financial'), ('Volunteering', 'Volunteering'), ('Resources', 'Resources'), ('Skills', 'Skills'), ('Other', 'Other')], default='financial', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contributions',
            name='description',
            field=models.CharField(default='description', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contributions',
            name='time_commit',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='requests',
            name='description',
            field=models.CharField(default='description', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='requests',
            name='location',
            field=models.CharField(default='location', max_length=350),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='requests',
            name='ref_image',
            field=models.ImageField(default=111, upload_to=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='requests',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Reviewed', 'Reviewed')], default='Pending', max_length=20),
        ),
    ]
