# Generated by Django 5.1.4 on 2025-03-17 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_projectimages_image_services'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='council',
            name='phone',
            field=models.CharField(max_length=13),
        ),
    ]
