# Generated by Django 5.1.4 on 2025-03-17 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_customuser_managers_alter_council_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='council',
            name='phone',
            field=models.CharField(max_length=17),
        ),
    ]
