# Generated by Django 5.1.4 on 2025-03-18 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_projects_duration_projects_end_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='start_date',
        ),
        migrations.AlterField(
            model_name='projects',
            name='end_date',
            field=models.DateField(),
        ),
    ]
