# Generated by Django 5.1.4 on 2025-03-18 11:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_remove_projects_start_date_alter_projects_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
