# Generated by Django 5.1.4 on 2025-03-18 12:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_projects_start_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectimages',
            name='project',
        ),
        migrations.AddField(
            model_name='projects',
            name='image',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='projectImages', to='api.projectimages', to_field='image'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='projectimages',
            name='image',
            field=models.ImageField(unique=True, upload_to='project_images/'),
        ),
    ]
