# Generated by Django 5.1.4 on 2025-03-18 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_remove_projectimages_project_projects_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectimages',
            old_name='image',
            new_name='media',
        ),
    ]
